### PR TITLE
Better Beginnings Mod Faithful

### PR DESCRIPTION
**Pull request by phuccom000**
I create this myself with the base is the faithful resource pack. i hope it will be accepted. it's not finished yet thou

### CODE REVIEW

**Comment by MarikCZ** [comment]
I think, these textures are not so ugly as my... - No worries! :D

**Comment by phuccom000** [comment]
hi

**Comment by xMrVizzy** [comment]
Cool, I will check some of that textures!

**Comment by xMrVizzy** [comment]
@phuccom000 can you change all furnaces textures, it's good, but border in 2 pixel is so ugly, realy

**Pull request closed without merging**
