### PR TITLE
Next Forestry textures + Tech_Reborn update!

### PR DESCRIPTION
**Pull request by MarikCZ**
I agree with your rule - you can delete ugly textures without asking!
PS: Forestry contains my older textures from year 2014...

### CODE REVIEW

**Comment by xMrVizzy** [comment]
Nice!

**Comment by xMrVizzy** [comment]
I close pull request and uploade best textures yourself, i add your name in commit name

**Comment by MarikCZ** [comment]
BTW: I collected next 500 textures - pull request soon.

Dne 1.3.2017 18:31 napsal uživatel "Alexey Krainev" <
notifications@github.com>:

**Comment by xMrVizzy** [comment]
kk

**Comment by MarikCZ** [comment]
Can you add me push access permission? It will be easier for me... :)

**Pull request closed without merging**
